services:

  backend:
    build: ./backend
    container_name: ecommerce_backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: ecommerce_frontend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app

    depends_on:
      - backend